---
title: NE in continuous games
---

So far, we have restricted attention to computing Nash equilibrium in finite games. In this section, we look at continuous games, i.e., games where the strategy spaces are continuous sets, primarily focusing on the case where the strategy space of each player is a subset of $\reals$. The examples in this section are adapted from @Gibbons1992 and @Harrington2014.

Suppose that the utility function is continuous in $\ALPHABET S$ and quasi-concave in $\ALPHABET S_i$. Then, by @thm-NE-pure, the game has NE in pure strategies. In principle, for games where $\ALPHABET S_i \subseteq \reals$, finding such a pure strategy NE is straight forward: [draw the best response curves of all players and find their point of intersection!]{.text-primary} In fact, we have already done that without explicitly stating it.

Recall the game of Cournot competition defined in @sec-cournot for $n = 2$ players. In this case, $\ALPHABET S_1 = \ALPHABET S_2 = [0, M]$ and 
$$
  u_i(s_1, s_2) = s_i \cdot (p(s_1 + s_2) - c)
$$
where the price function is $p(a) = \max\{ M - a, 0 \}$. 

As we had shown in @sec-cournot, the best response curves of the two players are
$$
  \BR_1(s_2) = \frac{M - c -s_2}{2}
  \quad\text{and}\quad
  \BR_2(s_1) = \frac{M - c - s_1}{2}.
$$
which are plotted below:

{{< include diagrams/cournot-competition.qmd >}}

In @sec-cournot, we had shown that the intersection point of these two best response curve is the unique rationalizable strategy (and therefore a NE). In general, even when the intersection point of the best response curves is not rationalizable, it is a NE.



## Bertrand competition with differentiated products {#sec-bertrand}

This model, proposed by @Bertrand1883, may be viewed as a generalization of Cournot competition where players set the prices rather than production levels. 

We consider a _differentiated product_ market with two firms. Firm $i \in \{1,2\}$ sets a price $p_i \in \reals_{\ge 0}$ and incurs a has a constant marginal production cost of $c$ (i.e., each firm has a cost of $c$ to produce one unit of goods, and as was the case in cournot competition, we assume that this case is the same for both firms). 

The demand of firm $i$ is a function of the curve and is captured by a demand curve $D_i(p_i, p_j)$, which is a weakly decreasing function of its own price and a weakly increasing function of the prices of the other firm.

Thus, the utility of each firm is
$$
  u_i(p_i, p_j) = (p_i - c) D_i(p_i, p_j).
$$

For simplicity, we will assume that the demand function is
$$
  D(p_i, p_j) = \max\{ P - p_i + a p_j, 0 \}
$$
where $P$ is a constant known as market potential. Thus, the utility of each firm is
$$
  u_i(p_i, p_j) = (p_i - c) \max\{ P - p_i + a p_j, 0 \}.
$$

Note that $u_i$ is a continuous function of $(p_i, p_j)$ and is quasi-concave in $p_i$. But, the strategy spaces are not compact. Therefore, @thm-NE-pure is not directly applicable. Nonetheless, it can be shown that the game has a pure strategy NE.

To find the NE, we look at the best response curves, which are obtained by setting $∂u_i/∂p_i = 0$ (and assuming that $p_i < P + a p_j$, so that we can ignore the max in the demand function):
$$
  \BR_i(p_j) = \tfrac 12 ( P + a p_j + c), \quad i, j \in \{1,2\}, i \neq j.
$$
Solving the above system of equations, we get
$$
  p_1 = p_2 = \frac{P + c}{2 - a}.
$$

## Final offer arbitration

In this section, we present a model of final offer arbitrary based on @Farber1980. To avoid terminology from labor markets, we model this as a resource allocation problem. 

An arbitrartor wants to split an infinitesimally divisible scalar-valued resource between two players in a fair manner. For the ease of notation, we will assume that the resouce has size 1, but it will be clear from the analysis that the size of the resource does not matter. 

The division of the resource works as follows. Both players simultaneously propose the amount of resource that should be allocated to player 1. Let $s_1$ and $s_2$ denote their proposals. There is an arbitrator, who has its own assessment of a _fair_ allocation to player 1. Let $X$ denote the arbitrators assessment, which is a random variable with CDF $F_X$ (and PDF $f_X$). The arbitrator chooses the proposal (for the allocation to player 1) that is closest to its own assessment. Thus, the allocation to player 1 is

- $s_1$ if $|x - s_1| \le |s_2 - x|$
- $s_2$ if $|x - s_1| > |s_2 - x|$

We will assume that $s_1 < s_2$ and drop the absolute value signs. Thus, 
$$
  \PR(\text{allocation is $s_1$}) = \PR\left( x \le \frac{s_1 + s_2}{2} \right) = F_X\left(\frac{s_1 + s_2}{2} \right).
$$
Similarly,
$$
  \PR(\text{allocation is $s_2$}) = \PR\left( x > \frac{s_1 + s_2}{2} \right) = 1 - F_X\left(\frac{s_1 + s_2}{2} \right).
$$

Let $A_1$ denote the allocation to player 1. Then,
$$
  \EXP[A_1] = s_1 F_X\left(\frac{s_1 + s_2}{2}\right)
          + s_2 \left( 1 -  F_X\left(\frac{s_1 + s_2}{2}\right) \right)
$$
Since the total resource is 1, the allocation $A_2$ to player 2 is
$$
  \EXP[A_2] = 1 - \EXP[A_1].
$$

Player 1 wants to maximize $\EXP[A_1]$ and player 2 want to maximize $\EXP[A_2]$, where $\EXP[A_1] + \EXP[A_2] = 1$ (which is the size of the resource). Thus, this is constant-sum game and we can treat is as a zero-sum game where player 1 wants to maximize $\EXP[A_1]$ and plyaer 2 wants to minimize $\EXP[A_1]$. 

To find the NE, we look at the best response curves, which are obtained by setting $∂\EXP[A_1]/∂s_1$ and $∂\EXP[A_1]/∂s_2$ to zero:
\begin{align*}
  F_X\left(\frac{s_1 + s_2}{2} \right)
  &= \left( \frac{s_2 - s_1}{2} \right)
     f_X\left(\frac{s_1 + s_2}{2}\right) \\
  1 - F_X\left(\frac{s_1 + s_2}{2} \right)
  &= \left( \frac{s_2 - s_1}{2} \right)
     f_X\left(\frac{s_1 + s_2}{2}\right) 
\end{align*}
Thus, at equilibrium, we must have that
\begin{align*}
  s_1 + s_2 &= 2 F^{-1}_X\left(\frac 12 \right) \\
  s_2 - s_1 &= \frac{1}{f_X\left(\frac{s_1 + s_2}{2}\right)}
\end{align*}
Thus,
\begin{align*}
  s_1 &= F_X^{-1}\left(\frac{1}{2}\right) 
  - \frac{1}{2 f_X\left(F_X^{-1}(\tfrac 12)\right)} \\
  s_2 &= F_X^{-1}\left(\frac{1}{2}\right) 
  + \frac{1}{2 f_X\left(F_X^{-1}(\tfrac 12)\right)} \\
\end{align*}

For example, if $X \sim \mathcal{N}(μ, σ^2)$, then the median $F_X^{-1}(0.5)$ is same as the mean (since the distribution is symmetric around the mean). Thus,
$$
  s_1 = μ - \sqrt{\frac{π}{2}}\, σ ,
  \quad
  s_2 = μ + \sqrt{\frac{π}{2}}\, σ.
$$

## Some examples

:::{#exm-quadratic-game}
### Quadratic Games
Consider a two-player game with $\ALPHABET {S}_1 = \ALPHABET {S}_2 = [0, \infty)$. The utility functions of the players are as follows:  
\begin{align*}
    u_1(s_1, s_2) &= s_1(s_2 - s_1), \\
    u_2(s_1, s_2) &= s_2(1 - s_1 - s_2).
\end{align*}

Find *all* pure strategy Nash equilibria of the game.
:::

:::{.callout-note}
### Solution

Observe that the utility function of both players is continuous and differentiable in \( (s_1, s_2) \) and is convex in their own strategy. So, we try to find the pure strategy NE by looking for the point of intersection of the best responses (BR).  

To find the BR of player 1, we compute \( ∂u_1/∂s_1 \) and set it to zero:  
$$
\frac{∂u_1}{∂s_1} = s_2 - 2s_1 = 0 
\implies
s_1 = \frac{1}{2} s_2.
$$

Thus,  
$$ \BR_1(s_2) = \frac{1}{2} s_2. $$

To find the BR of player 2, we compute \( ∂u_2/∂s_2 \) and set it to zero:  
$$
\frac{∂u_2}{∂s_2} = 1 - s_1 - 2s_2
\implies
s_2 = \frac{1}{2} (1 - s_1).
$$

Thus,
$$ \BR_2(s_1) = \frac{1}{2} (1 - s_1). $$

Thus, the NE, if it exists, is given by  
$$
s_1 = \BR_1(s_2) 
\quad
s_2 = \BR_2(s_1).
$$

Thus,  
$$
s_1 = \frac{1}{4}(1 - s_1) \implies s_1 = \frac{1}{5}.
$$
and  
$$
s_2 = \frac{1}{2}\left(1 - \frac{s_2}{2}\right)
\implies 
s_2 = \frac{2}{5}.
$$

Thus, the **unique** NE of the game is $(1/5, 2/5)$.

:::

## Problem of the commons
