on:
  push:
    branches: quarto

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
          # with:
          # To install LaTeX to build PDF book 
          # tinytex: true 
          # uncomment below and fill to pin a version
          # version: SPECIFIC-QUARTO-VERSION-HERE
      
      - name: Fix timestamps
        run:  bash .github/scripts/fix-timestamps

      - name: Render and publish website
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

